# Example 6:
# This is an example action to build and release your app for
# Linux x64, Windows x64, macOS x64 and macOS Arm64 (M1 and above).
# The steps this workflow takes are:
#
# STEPS:
# - Checkout the repository using actions/checkout@v4
# - Install Linux system dependencies required to build the app.
# - Set up Node LTS and a cache for global npm/yarn/pnpm package data using actions/setup-node@v4.
# - Set up Rust and a cache for the target/ folder using dtolnay/rust-toolchain@stable and swatinem/rust-cache@v2.
# - Install the frontend dependencies and, if not configured as beforeBuildCommand, run the web app's build script.
# - Finally, it uses tauri-apps/tauri-action@v0 to run tauri build, generate the artifacts, and create the GitHub release.

name: 'publish'

on:
  push:
    branches:
      - release
  workflow_dispatch: # Manual release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        settings:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.settings.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu only)
        if: matrix.settings.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
        working-directory: example6

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: example6/package-lock.json

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.settings.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          # Adjust the path to point to the src-tauri directory within example6
          workspaces: 'example6/src-tauri -> target'

      - name: Install frontend dependencies
        run: npm install
        working-directory: example6

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.settings.args }}
        # working-directory: example6/src-tauri # This is crucial for Tauri commands
