name: 'Publish Tauri App'

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build-and-release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''
    runs-on: ${{ matrix.include.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install System Dependencies (Ubuntu only)
        if: matrix.include.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
        working-directory: example6

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'yarn'
          cache-dependency-path: example6/yarn.lock

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.include.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Cache Rust Target Folder
        uses: swatinem/rust-cache@v2
        with:
          # Adjusted path for workspaces to match the project directory structure
          workspaces: 'example6/src-tauri -> target'

      - name: Install Frontend Dependencies
        run: yarn install
        working-directory: example6

      - name: Build and Release with Tauri
        uses: tauri-apps/tauri-action@v0
        with:
          args: ${{ matrix.include.args }}
          projectPath: example6 # Setting projectPath to match your project directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
